keys:
  - &admin_key age19nfhz30pwa0frjmmg05asge4659t48suvw023wvf9wkulhwclqlqy6wuld
  - &celestia_key age1r4mta98wtaacaf92m6nap3stj3ds0vu9gqxff0572kls6m8mjguq4fr565
  - &celestialserver_key age1vwgt293s04zz2rud5qt2y3gh3vlznget645xgns9ra0uyluk6vsqtf7r0l
creation_rules:
  - path_regex: celestia/[^/]+
    key_groups:
      - age:
          - *admin_key
          - *celestia_key
  - path_regex: celestialserver/[^/]+
    key_groups:
      - age:
          - *admin_key
          - *celestialserver_key
