# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c0f1789f-edad-44d9-92ed-6eb4c543ea8c";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-c0f1789f-edad-44d9-92ed-6eb4c543ea8c".device = "/dev/disk/by-uuid/c0f1789f-edad-44d9-92ed-6eb4c543ea8c";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-c0f1789f-edad-44d9-92ed-6eb4c543ea8c";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-c0f1789f-edad-44d9-92ed-6eb4c543ea8c";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6A86-2AB2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a7bd9db4-4f79-4b84-a32b-effa485bd4e0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
